export const INICIO_CARGANDO_CATEGORIAS='INICIO_CARGANDO_CATEGORIAS';
export const FIN_CARGANDO_CATEGORIAS='FIN_CARGANDO_CATEGORIAS';
export const SET_CATEGORIAS='SET_CATEGORIAS';

export const INICIO_CARGANDO_PRODUCTOS='INICIO_CARGANDO_PRODUCTOS';
export const FIN_CARGANDO_PRODUCTOS='FIN_CARGANDO_PRODUCTOS';
export const SET_PRODUCTOS='SET_PRODUCTOS';
export const SET_SELECCIONAR_PRODUCTO='SET_SELECCIONAR_PRODUCTO';
export const ESTADO_PRODUCTO='ESTADO_PRODUCTO';

export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const SUMAR_CARRITO = "SUMAR_CARRITO";
export const RESTAR_CARRITO = "RESTAR_CARRITO";
export const ELIMINAR_TODO_CARRITO = "ELIMINAR_TODO_CARRITO";

export const INICIO_CARGANDO_LOGIN = 'INICIO_CARGANDO_LOGIN';
export const FIN_CARGANDO_LOGIN = 'FIN_CARGANDO_LOGIN';
export const SET_SUCCESS_LOGIN = 'SET_SUCCESS_LOGIN';
export const SET_CERRAR_LOGIN='SET_CERRAR_LOGIN';

export const INICIO_CARGANDO_CLIENTE = 'INICIO_CARGANDO_CLIENTE';
export const FIN_CARGANDO_CLIENTE = 'FIN_CARGANDO_CLIENTE';
export const SET_REGISTER_CLIENTE = 'SET_REGISTER_CLIENTE';

// TIPO DOCUEMNTO
export const INICIO_CARGANDO_TIPODOCUMENTO='INICIO_CARGANDO_TIPODOCUMENTO';
export const FIN_CARGANDO_TIPODOCUMENTO='FIN_CARGANDO_TIPODOCUMENTO';
export const SET_TIPODOCUMENTO='SET_TIPODOCUMENTO';

//  TIPO USUARIO
export const INICIO_CARGANDO_TIPOUSUARIO='INICIO_CARGANDO_TIPOUSUARIO';
export const FIN_CARGANDO_TIPOUSUARIO='FIN_CARGANDO_TIPOUSUARIO';
export const SET_TIPOUSUARIO='SET_TIPOUSUARIO';

//FAVORITOS
export const AGREGAR_FAVORITO = "AGREGAR_FAVORITO";
export const ELIMINAR_FAVORITO = "ELIMINAR_FAVORITO";
export const SUMAR_FAVORITO = "SUMAR_FAVORITO";
export const RESTAR_FAVORITO = "RESTAR_FAVORITO";
export const ELIMINAR_TODO_FAVORITO = "ELIMINAR_TODO_FAVORITO";

//  TIPO MONEDA
export const INICIO_CARGANDO_TIPOMONEDA='INICIO_CARGANDO_TIPOMONEDA';
export const FIN_CARGANDO_TIPOMONEDA='FIN_CARGANDO_TIPOMONEDA';
export const SET_TIPOMONEDA='SET_TIPOMONEDA';

//  TIPO COMPROBANTE
export const INICIO_CARGANDO_TIPOCOMPROBANTE='INICIO_CARGANDO_TIPOCOMPROBANTE';
export const FIN_CARGANDO_TIPOCOMPROBANTE='FIN_CARGANDO_TIPOCOMPROBANTE';
export const SET_TIPOCOMPROBANTE='SET_TIPOCOMPROBANTE';

export const SET_PAGO= 'SET_PAGO';