export const INICIO_CARGANDO_CATEGORIAS='INICIO_CARGANDO_CATEGORIAS';
export const FIN_CARGANDO_CATEGORIAS='FIN_CARGANDO_CATEGORIAS';
export const SET_CATEGORIAS='SET_CATEGORIAS';

export const INICIO_CARGANDO_PRODUCTOS='INICIO_CARGANDO_PRODUCTOS';
export const FIN_CARGANDO_PRODUCTOS='FIN_CARGANDO_PRODUCTOS';
export const SET_PRODUCTOS='SET_PRODUCTOS';
export const SET_SELECCIONAR_PRODUCTO='SET_SELECCIONAR_PRODUCTO';

export const AGREGAR_CARRITO = "AGREGAR_CARRITO";
export const ELIMINAR_CARRITO = "ELIMINAR_CARRITO";
export const SUMAR_CARRITO = "SUMAR_CARRITO";
export const RESTAR_CARRITO = "RESTAR_CARRITO";
export const ELIMINAR_TODO_CARRITO = "ELIMINAR_TODO_CARRITO";

export const INICIO_CARGANDO_LOGIN = 'INICIO_CARGANDO_LOGIN';
export const FIN_CARGANDO_LOGIN = 'FIN_CARGANDO_LOGIN';
export const SET_SUCCESS_LOGIN = 'SET_SUCCESS_LOGIN';

export const INICIO_CARGANDO_CLIENTE = 'INICIO_CARGANDO_CLIENTE';
export const FIN_CARGANDO_CLIENTE = 'FIN_CARGANDO_CLIENTE';
export const SET_REGISTER_CLIENTE = 'SET_REGISTER_CLIENTE';