# Generated by Django 3.2.8 on 2021-10-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('numro_documento', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.rol')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.tipodocumento')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_comprobante', models.CharField(max_length=50)),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha de Ingreso')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.18, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.moneda')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.tipocomprobante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True)),
                ('representante', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.categoria')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.proveedor')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_comprobante', models.CharField(max_length=50)),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha de Ingreso')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0.18, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.proveedor')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.tipocomprobante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=4)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.producto')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tienda.producto')),
            ],
        ),
    ]
